version: "3"
services:
  app:
    container_name: app
    build: .
    command: node server.mjs
    ports: 
      - "8080:8080"
    links:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"